## 第一部分： 基础信息
name: espressif_esp32_s3                        # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: master                                # <必选项> 组件版本号
description: driver & sdk for mcu esp32-s3      # <必选项> 建议至少20字以上
type: chip                                      # <必选项> 组件类型，为：solution, chip, board, common, sdk

tag: 核心模块                                    # <可选项> 组件分类，缺省值： ''
keywords:                                       # <可选项> 标签，会影响到组件被搜索的效果，合理的标签很重要
  - base
license: Apache license v2.0                    # <可选项> 源代码的许可证，要确保所有代码、文件的许可证不冲突。如：MIT，Apache license v2.0，BSD

# 指定该组件依赖的组件及版本，版本支持条件比较，支持：>=v1.0, >v1.0, ==v1.0, <=v1.0, <v1.0, v1.0
# 未指定条件时，默认为 ==，如 v1.0 与 ==v1.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
  # - libc_stub: master
#   - aos: >=v7.2.0

## 第四部分：编译连接信息
# build_config:                            # <可选项> 编译配置项
#   include:                               # <可选项> 编译时，影响编译器的-I 参数 ,全局有效
#     - src                                #        include 只能是该软件包下的目录，不能使用外部目录
#   internal_include:                      # <可选项> 编译时，影响编译器的-I 参数 ,组件内有效
#     - include
#   cflag: ''                              # <可选项> C 编译器所需要要的编译参数
#   cxxflag: ''                            # <可选项> CXX 编译器所需要要的编译参数
#   asmflag: ''                            # <可选项> 汇编器所需要要参数
#   define:                                # <可选项> 宏定义, 增加编译器的-D 选项,如：
#     XXX: 1                               #   -DXXX=1
#     AAA: 1                               #   -DAAA
#     STR: "abc"                           #   -DSTR="abc"
#   libs:                                  # 该组件中支持的二进制静态库,如：libxxx.a, libyyy.a
#     - xxx                                #   -lxxx
#     - yyy                                #   -lyyy
#   libpath:                               # 指定静态库所在的路径（相对于该组件路径）
#     - libs                               #   -Llibs
build_config:
  # prebuild_script:
  cflag: >
    -mlongcalls -Wno-frame-address -Wno-clobbered -Wno-deprecated-declarations -Wno-missing-field-initializers
    -fno-tree-switch-conversion -fno-jump-tables -DKERNEL=FREERTOS

  cxxflag: >
    -mlongcalls -Wno-frame-address -Wno-clobbered -Wno-deprecated-declarations -Wno-missing-field-initializers
    -std=gnu++11 -fno-exceptions -fno-rtti -fno-tree-switch-conversion -fno-jump-tables -fpermissive -DKERNEL=FREERTOS

  ldflag: >
    -mlongcalls -z muldefs -Wl,--gc-sections  -fno-rtti  -fno-lto
    -mfix-esp32-psram-cache-issue  -mfix-esp32-psram-cache-strategy=memw
    -uesp_app_desc  -Wl,--wrap=vPortCleanUpTCB  -upthread_include_pthread_impl  -upthread_include_pthread_cond_impl
    -upthread_include_pthread_local_storage_impl  -upthread_include_pthread_rwlock_impl
    -uld_include_highint_hdl  -ustart_app  -ustart_app_other_cores  -u__ubsan_include
    -Wl,--wrap=longjmp  -uvfs_include_syscalls_impl  -Wl,--undefined=uxTopUsedPriority -uapp_main -lm
    -unewlib_include_heap_impl -unewlib_include_syscalls_impl -unewlib_include_pthread_impl -unewlib_include_assert_impl
    -Wl,--wrap=_Unwind_SetEnableExceptionFdeSorting  -Wl,--wrap=__register_frame_info_bases
    -Wl,--wrap=__register_frame_info  -Wl,--wrap=__register_frame  -Wl,--wrap=__register_frame_info_table_bases
    -Wl,--wrap=__register_frame_info_table  -Wl,--wrap=__register_frame_table  -Wl,--wrap=__deregister_frame_info_bases
    -Wl,--wrap=__deregister_frame_info  -Wl,--wrap=_Unwind_Find_FDE  -Wl,--wrap=_Unwind_GetGR
    -Wl,--wrap=_Unwind_GetCFA  -Wl,--wrap=_Unwind_GetIP  -Wl,--wrap=_Unwind_GetIPInfo
    -Wl,--wrap=_Unwind_GetRegionStart  -Wl,--wrap=_Unwind_GetDataRelBase  -Wl,--wrap=_Unwind_GetTextRelBase
    -Wl,--wrap=_Unwind_SetIP  -Wl,--wrap=_Unwind_SetGR  -Wl,--wrap=_Unwind_GetLanguageSpecificData
    -Wl,--wrap=_Unwind_FindEnclosingFunction  -Wl,--wrap=_Unwind_Resume  -Wl,--wrap=_Unwind_RaiseException
    -Wl,--wrap=_Unwind_DeleteException  -Wl,--wrap=_Unwind_ForcedUnwind  -Wl,--wrap=_Unwind_Resume_or_Rethrow
    -Wl,--wrap=_Unwind_Backtrace  -Wl,--wrap=__cxa_call_unexpected  -Wl,--wrap=__gxx_personality_v0
    -u__cxa_guard_dummy  -lstdc++  -lgcc -u__cxx_fatal_exception -lgcov -lc
    -Tesp32s3.rom.api.ld -Tesp32s3.rom.ld  -Tesp32s3.rom.libgcc.ld  -Tesp32s3.rom.newlib.ld
    -Tesp32s3.rom.version.ld -Tesp32s3.peripherals.ld -Tmemory.ld -Tsections.ld -z muldefs

  include:
    - ../espressif_idf/esp-idf/components/esp_ringbuf/include
    - ../espressif_idf/esp-idf/components/newlib/platform_include
    - ../espressif_idf/esp-idf/components/freertos/include
    - ../espressif_idf/esp-idf/components/freertos/xtensa/include
    - ../espressif_idf/esp-idf/components/freertos/port/xtensa/include
    - ../espressif_idf/esp-idf/components/esp_hw_support/include
    - ../espressif_idf/esp-idf/components/hal/include
    - ../espressif_idf/esp-idf/components/hal/esp32s3/include
    - ../espressif_idf/esp-idf/components/heap/include
    - ../espressif_idf/esp-idf/components/log/include
    - ../espressif_idf/esp-idf/components/lwip/include/apps
    - ../espressif_idf/esp-idf/components/lwip/include/apps/sntp
    - ../espressif_idf/esp-idf/components/lwip/lwip/src/include
    - ../espressif_idf/esp-idf/components/lwip/port/esp32/include
    - ../espressif_idf/esp-idf/components/lwip/port/esp32/include/arch
    - ../espressif_idf/esp-idf/components/soc/include
    - ../espressif_idf/esp-idf/components/soc/soc/include
    - ../espressif_idf/esp-idf/components/soc/soc/esp32s3/include
    - ../espressif_idf/esp-idf/components/soc/esp32s3/include
    - ../espressif_idf/esp-idf/components/soc/src/esp32s3/include
    - ../espressif_idf/esp-idf/components/esp_rom/include
    - ../espressif_idf/esp-idf/components/esp_rom/include/esp32
    - ../espressif_idf/esp-idf/components/esp_rom/esp32
    - ../espressif_idf/esp-idf/components/esp_common/include
    - ../espressif_idf/esp-idf/components/esp_system/include
    - ../espressif_idf/esp-idf/components/esp32/include
    - ../espressif_idf/esp-idf/components/esp32s3/include
    - ../espressif_idf/esp-idf/components/xtensa/include
    - ../espressif_idf/esp-idf/components/xtensa/esp32/include
    - ../espressif_idf/esp-idf/components/driver/include
    - ../espressif_idf/esp-idf/components/driver/esp32/include
    - ../espressif_idf/esp-idf/components/efuse/include
    - ../espressif_idf/esp-idf/components/efuse/esp32/include
    - ../espressif_idf/esp-idf/components/vfs/include
    - ../espressif_idf/esp-idf/components/esp_wifi/include
    - ../espressif_idf/esp-idf/components/esp_event/include
    - ../espressif_idf/esp-idf/components/esp_netif/include
    - ../espressif_idf/esp-idf/components/esp_eth/include
    - ../espressif_idf/esp-idf/components/tcpip_adapter/include
    - ../espressif_idf/esp-idf/components/esp_ipc/include
    - ../espressif_idf/esp-idf/components/app_trace/include
    - ../espressif_idf/esp-idf/components/esp_timer/include
    - ../espressif_idf/esp-idf/components/mbedtls/port/include
    - ../espressif_idf/esp-idf/components/mbedtls/mbedtls/include
    - ../espressif_idf/esp-idf/components/mbedtls/esp_crt_bundle/include
    - ../espressif_idf/esp-idf/components/app_update/include
    - ../espressif_idf/esp-idf/components/spi_flash/include
    - ../espressif_idf/esp-idf/components/bootloader_support/include
    - ../espressif_idf/esp-idf/components/nvs_flash/include
    - ../espressif_idf/esp-idf/components/pthread/include
    - ../espressif_idf/esp-idf/components/esp_gdbstub/include
    - ../espressif_idf/esp-idf/components/esp_gdbstub/xtensa
    - ../espressif_idf/esp-idf/components/esp_gdbstub/esp32
    - ../espressif_idf/esp-idf/components/espcoredump/include
    - ../espressif_idf/esp-idf/components/wpa_supplicant/include
    - ../espressif_idf/esp-idf/components/wpa_supplicant/port/include
    - ../espressif_idf/esp-idf/components/wpa_supplicant/include/esp_supplicant
    - ../espressif_idf/esp-idf/components/asio/asio/asio/include
    - ../espressif_idf/esp-idf/components/asio/port/include
    - ../espressif_idf/esp-idf/components/bt/host/nimble/nimble/porting/nimble/include
    - ../espressif_idf/esp-idf/components/bt/host/nimble/port/include
    - ../espressif_idf/esp-idf/components/bt/host/nimble/nimble/nimble/include
    - ../espressif_idf/esp-idf/components/bt/host/nimble/nimble/nimble/host/include
    - ../espressif_idf/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/ans/include
    - ../espressif_idf/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/bas/include
    - ../espressif_idf/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/dis/include
    - ../espressif_idf/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/gap/include
    - ../espressif_idf/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/gatt/include
    - ../espressif_idf/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/ias/include
    - ../espressif_idf/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/ipss/include
    - ../espressif_idf/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/lls/include
    - ../espressif_idf/esp-idf/components/bt/host/nimble/nimble/nimble/host/services/tps/include
    - ../espressif_idf/esp-idf/components/bt/host/nimble/nimble/nimble/host/util/include
    - ../espressif_idf/esp-idf/components/bt/host/nimble/nimble/nimble/host/store/ram/include
    - ../espressif_idf/esp-idf/components/bt/host/nimble/nimble/nimble/host/store/config/include
    - ../espressif_idf/esp-idf/components/bt/host/nimble/nimble/porting/npl/freertos/include
    - ../espressif_idf/esp-idf/components/bt/host/nimble/esp-hci/include
    - ../espressif_idf/esp-idf/components/fatfs/diskio
    - ../espressif_idf/esp-idf/components/fatfs/vfs
    - ../espressif_idf/esp-idf/components/fatfs/src
    - ../espressif_idf/esp-idf/components/cbor/port/include
    - ../espressif_idf/esp-idf/components/unity/include
    - ../espressif_idf/esp-idf/components/unity/unity/src
    - ../espressif_idf/esp-idf/components/coap/port/include
    - ../espressif_idf/esp-idf/components/coap/libcoap/include
    - ../espressif_idf/esp-idf/components/console
    - ../espressif_idf/esp-idf/components/nghttp/port/include
    - ../espressif_idf/esp-idf/components/nghttp/nghttp2/lib/includes
    - ../espressif_idf/esp-idf/components/esp-tls
    - ../espressif_idf/esp-idf/components/esp_adc_cal/include
    - ../espressif_idf/esp-idf/components/esp_hid/include
    - ../espressif_idf/esp-idf/components/tcp_transport/include
    - ../espressif_idf/esp-idf/components/esp_http_client/include
    - ../espressif_idf/esp-idf/components/esp_http_server/include
    - ../espressif_idf/esp-idf/components/esp_https_ota/include
    - ../espressif_idf/esp-idf/components/protobuf-c/protobuf-c
    - ../espressif_idf/esp-idf/components/protocomm/include/common
    - ../espressif_idf/esp-idf/components/protocomm/include/security
    - ../espressif_idf/esp-idf/components/protocomm/include/transports
    - ../espressif_idf/esp-idf/components/mdns/include
    - ../espressif_idf/esp-idf/components/esp_local_ctrl/include
    - ../espressif_idf/esp-idf/components/sdmmc/include
    - ../espressif_idf/esp-idf/components/esp_serial_slave_link/include
    - ../espressif_idf/esp-idf/components/esp_websocket_client/include
    - ../espressif_idf/esp-idf/components/expat/expat/expat/lib
    - ../espressif_idf/esp-idf/components/expat/port/include
    - ../espressif_idf/esp-idf/components/wear_levelling/include
    - ../espressif_idf/esp-idf/components/freemodbus/common/include
    - ../espressif_idf/esp-idf/components/idf_test/include
    - ../espressif_idf/esp-idf/components/idf_test/include/esp32
    - ../espressif_idf/esp-idf/components/jsmn/include
    - ../espressif_idf/esp-idf/components/json/cJSON
    - ../espressif_idf/esp-idf/components/libsodium/libsodium/src/libsodium/include
    - ../espressif_idf/esp-idf/components/libsodium/port_include
    - ../espressif_idf/esp-idf/components/mqtt/esp-mqtt/include
    - ../espressif_idf/esp-idf/components/openssl/include
    - ../espressif_idf/esp-idf/components/perfmon/include
    - ../espressif_idf/esp-idf/components/spiffs/include
    - ../espressif_idf/esp-idf/components/ulp/include
    - ../espressif_idf/esp-idf/components/wifi_provisioning/include
    - ../espressif_idf/esp-idf/components/freertos/include/esp_additions/freertos
    - ../espressif_idf/esp-idf/components/freertos/include/esp_additions
    - ../espressif_idf/esp-idf/components/esp_hw_support/include/soc
    - ../espressif_idf/esp-idf/components/hal/platform_port/include

  libs:
    - main
    - console
    - esp_gdbstub
    - esp_netif
    - esp_websocket_client
    - json
    - mqtt
    - sdmmc
    - wear_levelling
    - app_trace
    - cxx
    - esp_hid
    - esp_wifi
    - esp_pm
    - esp_rom
    - esp_hw_support
    - liblibsodium
    - newlib
    - soc
    - wifi_provisioning
    - app_update
    - driver
    - esp_http_client
    - expat
    - log
    - nghttp
    - spiffs
    - wpa_supplicant
    - asio
    - fatfs
    - efuse
    - esp_http_server
    - esp_ringbuf
    - lwip
    - nvs_flash
    - spi_flash
    - xtensa
    - bootloader_support
    - esp_adc_cal
    - esp_https_ota
    - freemodbus
    - openssl
    - tcpip_adapter
    - esp_common
    - esp_serial_slave_link
    - freertos
    - mbedcrypto
    - perfmon
    - tcp_transport
    - cbor
    - espcoredump
    - esp_ipc
    - esp_system
    - mbedtls
    - protobuf-c
    - ulp
    - esp_eth
    - esp_timer
    - heap
    - mbedx509
    - protocomm
    - unity
    - coap
    - esp_event
    - esp_local_ctrl
    - esp-tls
    - jsmn
    - mdns
    - pthread
    - vfs
    - coexist
    - net80211
    - core
    - espnow
    - mesh
    - pp
    - smartconfig
    - phy
    - hal
    - xt_hal
    - bt
    - btdm_app
    - btbb
    - esp_phy

  libpath:
    - ../espressif_idf/esp-idf/components/esp_rom/esp32s3/ld
    - ../espressif_idf/esp-idf/components/esp32s3/ld
    - ../espressif_idf/esp-idf/components/esp_wifi/lib/esp32s3
    - ../espressif_idf/esp-idf/components/xtensa/esp32s3
    - ../espressif_idf/esp-idf/components/esp_system/ld/esp32s3
    - ../espressif_idf/esp-idf/components/esp_phy/lib/esp32s3
    - ../espressif_idf/esp-idf/components/soc/esp32s3/ld
    - ../espressif_idf/esp-idf/components/bt/controller/lib_esp32c3_family/esp32s3

## 第五部分：配置信息
def_config:                              # 组件的可配置项
  IDF_VER: "35eebd69"
  ESP_PLATFORM: 1
  OS_FREERTOS: 1
  MBEDTLS_CONFIG_FILE: "mbedtls/esp_config.h"
  CONFIG_ESP_DISPATCHER_DELEGATE_TASK_CORE: 0
  CONFIG_ESP_DISPATCHER_DELEGATE_TASK_PRIO: 10
  CONFIG_ESP_DISPATCHER_DELEGATE_STACK_SIZE: 4096

hw_info:
  arch_name: xtensa
  cpu_name: esp32
  toolchain_prefix: xtensa-esp32s3-elf
  vendor_name: espressif
  ld_script: espressif_esp32_s3.lds

## 第六部分：安装信息
# install:
#   - dest: include/                       # 安装的目的路径 dest是相当路径，通常是相对于YoC SDK 安装目录
#     source:                              # 安装源列表
#      - src/*.h                           # 支持通配符，相对路径
# install:
#   - dest: "include"
#     source:
#       - hal/2ndboot/*.h
#       - aos/*.h
#       - aos/arch/*.h
#       - drivers/platform/hal/*.h
#       - drivers/platform/cmsis/inc/*.h
#       - drivers/rtos/rhino/cmsis/*.h
#       - drivers/utils/hwtimer_list/*.h
#       - drivers/platform/hal/haas1000/*.h
#       - drivers/services/wifi_app/alsa_adapter/*.h
#   - dest: "lib"
#     source:
#       - drivers/libmcuhaas1000.a ? <!CONFIG_A7_DSP_ENABLE>
#       - drivers/libmcuhaas1000_a7.a ? <CONFIG_A7_DSP_ENABLE>


## 第七部分：导出部分
# export:
#   - dest: "<SOLUTION_PATH>/generated/data" # 安装的目的路径 dest是相当路径
#     source:                                # 安装源列表
#       - "bootimgs/boot"
#       - "bootimgs/tee"
#       - "bootimgs/mtb"
#       - "configs/config.yaml"
